[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fitz>=0.0.1.dev2",
    "pandas>=2.3.0",
    "pdfplumber>=0.11.7",
    "pymupdf>=1.26.1",
    "streamlit>=1.45.1",
]
